### ISSUE TITLE
[BUG] 阅读模式显示有问题

### ISSUE THREAD

**Issue by Immortal-Sty** [LincZero/obsidian-any-block#1]
## 问题

该插件语法如下：

```markdown
[...]
- Center
  - First
    - 1
    - 2
  - Second
    - 3
    - 4
```

但进入阅读模式后，`[...]` 没有被隐藏，如图：

![](https://s3.bmp.ovh/imgs/2023/02/10/2e645e47fb239e31.png)

## 环境

- Windows 11 22H2
- Obsidian 1.1.9
- Any Block 1.2.4
- Theme: Minimal Theme

**Comment by LincZero** [comment]
已记录，会修复

**Comment by LincZero** [comment]
3240785ae47bbff155c40998e410ea8a9b8df950 修复后，后来又失效了
dd8961f1a42703c62185dcf2fdbbcee759e70bb3 再次修复
