### ISSUE TITLE
[Feature Request] 建议调整插件功能按钮与渲染块的相对位置以免遮蔽

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#10]
- 阅读视图模式下，当窗口窄小或渲染块太宽，右上角的插件功能按钮会遮挡住渲染块。
- 建议调整二者相对位置，让插件功能按钮比渲染块高一行以免遮蔽。

测试环境：
- Windows 11 22H2
- Obsidian 1.1.9 沙箱仓库初始设置（仅安装Any Block插件1.3.1）

![image](https://user-images.githubusercontent.com/20738431/219239236-e86875ab-60ab-4eed-a5eb-060d663a1f64.png)

**Comment by LincZero** [comment]
本来我是打算将这玩意应该是鼠标悬浮到转化快才显示的（像实时模式 的Edit this block 一样），太忙了忘记写了
位置我就不调了
