### ISSUE TITLE
[reinforce] list2mdtable style optimize

### ISSUE THREAD

**Issue by LincZero** [LincZero/obsidian-any-block#12]
list2mdtable 的行高较于 list2table会更高，原因：表格的内容是`<p>`标签，这个标签有行高。

那为什么自带的表格可以做到有样式的同时，行高较小？因为他不需要考虑换行。上下间隔可以设置为0。但如果换行了，上下间隔就会非常小，很拥挤。

可能会考虑的解决方案：
- 方案1. 识别单元格内容是否会进行换行（是否有换行符），若是，则设置内容的上下margin为0。若不是，维持原状
- 方案2. 使用first-child和last-child选择器，找到每个单元格的第一个和最后一个元素，分别清除top-margin和bottom-margin

**Comment by Linzeal** [comment]
速度好快，就解决了几个ISSUES。等你上架Obsidian插件市场了再试。

另外，额外说一些。

看了你的DEMO和一些代码，感觉你现在横向功能铺的太开，什么都想实现，但每个功能纵向深度又不够，不上不下的，炫技多过于实用，开发思路也因功能铺的过多而受干扰、受约束，光DEMO文件就好几个来介绍一堆的功能，你杂乱，用户用的就会更乱。因为绝大部分用户都是计算机小白，功能显现的太多会变得没有重点，反而对用户造成困难，不知所以。

**建议横向上做减法先将其他的功能统统砍掉，减少干扰，先集中一两个用户痛点做为特色功能，在它的纵向全流程上做加法做深加工，形成一个从渲染到可视化编辑的完整流程，先打造出一个功能黏性来。**（比如砍掉[2mermaid]、[2tab]这些，顺便可以等Obsidian先更新了mermaid后再来搞，可避免插件大小变得这么大）

例如表格是绝大多数Obsidian用户的痛点，不论是通过列表转的表格还是MD原表格，在增加表格的渲染样式和可视化编辑上都是痛点，可先集中对表格的处理这个功能，包括列表渲染为表格、同时让里面包含的MD代码可渲染、对MD原表格增加渲染，以及更关键的对渲染后的表格的可视化编辑。有了这个从渲染到可视化编辑的完整流程，AB就解决了用户对表格的痛点，黏性就会非常大。

有了一个功能的纵向完整流程，后面横向要增加转流程图[2flowchart]、转脑图[2mindmap]、转标签栏[2tab]等等其他功能的完整可视化流程的开发思路和路径就清晰了，也可交由其他插件在AB的API上去做，用户都不会轻易流失。

也即先深后广易，先广后深难。一点浅见。祝更好。
