### ISSUE TITLE
[BUG] 会把用`[ ]`括住的且前后无字符的内容误识别为选择器

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#15]
几天没关注，还没上Obsidian插件市场啊。

看到更新2.2了，顺手测试了下，提个bug：
- 会把用`[ ]`括住的且前后无字符的内容误识别为选择器。或许选择器的识别应当用严格模式，对生效的选择器建立有效列表，凡不在有效列表内的都不是选择器。

测试环境：
- Windows 11 22H2
- Obsidian 1.1.16 沙箱仓库中仅安装Any Block插件2.2.0

![image](https://user-images.githubusercontent.com/20738431/225308385-123a4e98-3b5c-4d3e-8073-9f89c2cc3299.png)

**Comment by LincZero** [comment]
## BUG

已在原代码中解决，下次更新就没有这个问题了。解决方法：

`reg_header:   /^((\s|>\s|-\s|\*\s|\+\s)*)(\[(.*)\])\s*$/`
修改为
`reg_header:   /^((\s|>\s|-\s|\*\s|\+\s)*)(\[(?!\[)(.*)\])\s*$/`

## 关于插件市场

进度：https://github.com/obsidianmd/obsidian-releases/pull/1662
插件的审核大概是每周末集中一次。

另外，开了个discussion，关于后续版本的一些想法：#14
