### ISSUE TITLE
[bug] 复选框列表不识别、列表转表格时列表中的行内代码符”`` ` ` ``“无法正确渲染

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#2]
## 列表转表格test

1. 列表中有行内代码符`` ` ` ``无法正确渲染
2. 列表中代码符`` ` ` ``里有`<`符号时渲染出错
3. 复选框列表的勾选框无法正确渲染
@LincZero 

测试环境：
- Windows 11 22H2
- Obsidian 1.1.9 沙箱仓库中仅安装Any Block插件1.2.4

![image](https://user-images.githubusercontent.com/20738431/218084315-095a7baf-38ed-47d3-9bf4-a8fff2767615.png)

**Comment by LincZero** [comment]
1. 复选框和有序列表问题已记录
2. 用md语法需要使用list2mdtable（而非list2table），哪怕是只使用了内联样式
_
list2mdtable会将单元格看成md、list2table会将单元格内容看成html内容
前者兼容后者，后者可以使用<br/>、<code>、<b>、<strong>来代替md语法，问题中有<符号出错是因为被识别为标签了
2mdtable更类似于原生的table，2table是简化版（节约性能啥的）

**Comment by Linzeal** [comment]
原来如此，明白了list2mdtable和list2table的区别及使用场景。

但我觉得在选择器上人为分为[list2mdtable]和[list2table]不太适合，纯属人为制造的问题。不论Any Block是否计划要做为一个平台提供API给其他插件，届时Any Block的用户肯定是世界各地、各式各样，一定会有很多用户不会去深入了解各选择器的使用要求，就会用着[list2table]但单元格里有MD的内联样式；或着是一开始有耐心去阅读使用须知从而知道各选择器的使用要求，看单元格没有MD的内联样式就使用了[list2table]选择器，但一段时间后单元格修改时无意间添加了MD的内联样式，这就出现了渲染出错，若是做为API数据出错就更麻烦。你无法预知用户会选择什么选择器、输入什么内容，性能更不是首要的，稳定及容错才是首要，性能待稳定后再去优化。因此，接口应当统一，少给用户做选择，就算有选择的事情也应当尽量交由代码代替人类去做。

因此，个人建议在用户层面无须提供多个同类的选择器，只提供一个统一选择器即可，并提高容错。如列表转表格，统一使用[list2table]，一律默认按同时有MD的内联样式和html语法标签来处理。至于性能优化，放到代码中去选择去优化。

**Comment by LincZero** [comment]
关了，复选框问题 #6，list2mdtable和list2table的问题需要先解决 #12
