### ISSUE TITLE
[FR] list2markmap

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#21]
使用了现在基于Mermaid的 list2mindmap ，感觉转化生成的mindmap好别扭，实在太丑了还不能像正常mindmap那样点击节点进行收起和展开。

看了github 里的[markmap](https://github.com/markmap/markmap)项目，markdown + mindmap ，这才是markdown里该有的mindmap，漂亮美观，也能正常节点进行收起和展开。Mermaid的 list2mindmap可以保留，建议新增一个基于markmap的mindmap转换处理器 list2markmap ，用于转换渲染为markmap。

markmap：
![image](https://user-images.githubusercontent.com/20738431/233790316-43a2a6b4-3559-40b8-b658-d5cf42b18ad3.png)

Mermaid mindmap：
![image](https://user-images.githubusercontent.com/20738431/233790344-51fda5ea-4a24-4b92-9eeb-5d6f0e4b5585.png)

**Comment by yett1873** [comment]
赞同。小白不太懂，如果只实现上述markmap的外观、不要求节点能够折叠的话，是不是把list2table的边框改成多种颜色的下划线就行了？
确实mermaid对格式的要求太严，加点md语法就各种报错，期待能把任意内容的多级列表转为树状图😊

**Comment by LincZero** [comment]
e6c3c3b3d404d456e41ebdf21cf5608d97f8720c

![图片](https://github.com/user-attachments/assets/fa76d1c4-2b0f-4409-910b-e0798458d866)
