### ISSUE TITLE
[BUG]list2mindmap报错，我查看了前边两个关闭问题，我在没有非法字符的情况下也不能使用

### ISSUE THREAD

**Issue by guanyubin** [LincZero/obsidian-any-block#23]
![image](https://github.com/LincZero/obsidian-any-block/assets/48738359/8b8d39a4-dd30-4d29-a972-4b8c8b3091eb)

[list2mindmap]
- 1
	- 1
- 2
	- 2
- 3
	- 3
- 3

**Comment by LincZero** [comment]
`[listroot(主题)|list2mindmap]`

这个的原因在于mermaid的mindmap需要一个中心节点（mermaid的这个确实不是太好用），直接在列表的外面加一层可能比较不优化，可以通过 `listroot` 的方式增加根节点，效果等同于

```
- a
  - 1
      - 1
  - 2
      - 2
  - 3
```

**Comment by LincZero** [comment]
程序上或者可以加一层判断：当没有中心节点时自动加一个。

但其实也不优雅，换 `markmind` 库还是最好的选择，对md和其他字符的支持也好
