### ISSUE TITLE
[BUG]预览模式下头部语句仍然显示

### ISSUE THREAD

**Issue by hsingll** [LincZero/obsidian-any-block#24]
问题和https://github.com/LincZero/obsidian-any-block/issues/1 一样
```
[list2mdtab]
- windows
	- 转到
- linux
```
效果：
<img width="664" alt="Snipaste_2023-07-31_09-42-55" src="https://github.com/LincZero/obsidian-any-block/assets/26346635/8bfea26f-e85f-4c2d-bab2-e32bcdb1ddec">

**Comment by LincZero** [comment]
是的，修复过一次。但再插件更新的过程中又出现了。
之前在ob社区中有人反馈过这个问题，这是之前的回答：

> 这是个比较难修的bug，其实我修复过一遍了（github issue的#1就是修复的这个问题）。前几个版本的any block应该是没有这个问题。
> 
> 后来不知道哪个版本改动了什么东西，这东西又自己跑出来了
> （估计是之前为了增加ab块嵌套ab块，增加了html转md的逻辑，导致逻辑被改了。大概是2.0.1~2.1.0之间的修改）
> 
> 暂时非常非常忙，抽不出空再修一遍（这东西修起来确实很麻烦）。
> 退版本的话……建议退2023年5月19日的commit版本，AB块不需要被引用/列表/AB块进行嵌套的话，区别应该不大

**Comment by LincZero** [comment]
借楼补充对该插件的规划：

这两周的周末我在抽时间学习markdown-it的插件开发（以下简称md-it），后面如果我还能抽出时间弄这个，我不会以维护这个插件的方式更新，而是会使用md-it重写。

这样做的好处：

1. 无论是使用Obsidian还是使用VuePress等其他渲染方式都能加载md-it库（举例一下，插件table extend就是使用了这种方式）。因为自搭的个人网站也非常需要这一插件进行渲染。
2. 可以引申一部分vuepress的md扩展语法进来，比如里面的 `:::` 符号。像这里的 `list2mdtab` 在VuePress语法里面其实是有的，并且那边的语法和渲染其实更成熟，你可以搜一下。
做一个Ob与md-it沟通“桥梁”，即可以给VuePresser提供一个更好的md编辑平台。也能从VuePress以及md-it插件社区中引入一些好用的工具。

当然，这是我能抽出空的前提，目前公司的新项目耗费了我非常多的精力。只有等该项目告一段落才能有精力做其他事。

**Comment by LincZero** [comment]
fix: e997d523f809adb9bb2ff7cfce40f107c07c4d34，正则匹配允许使用 `%%` 包裹头部，临时解决该问题。不用 `%%` 的前提下后续再怎么修

**Comment by LincZero** [comment]
dd8961f1a42703c62185dcf2fdbbcee759e70bb3

现在不用加 `%%` 也可以隐藏了
