### ISSUE TITLE
[bug] 有时候没有使用选择器也会被识别

### ISSUE THREAD

**Issue by wwjCMP** [LincZero/obsidian-any-block#26]
被误识别的结构如下

[[双链]]

# 一级标题

## 二级标题

**Comment by wwjCMP** [comment]
导致一些块在预览模式下被隐藏起来

**Comment by LincZero** [comment]
63a93bd183b48a8e8859808b8666f3a1cff2f20a

- [[...]] 不会再被误识别，仅 [...] 识别
- [...] 加两个空行，也不会被识别
