### ISSUE TITLE
[feature request] 列表转可折叠树形表格可否增加层次缩进和默认折叠

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#3]
更新到1.2.4，发现列表转可折叠树形表格[2lt]已经有了折叠三角形和点击折叠/展开的更新。使用后尚觉有待改进：

1. 层次缩进被折叠三角形占位了，同级的文字没有对齐。如上海市场部与销售部

![image](https://user-images.githubusercontent.com/20738431/218238032-38aa577f-822e-4021-a74f-416a01723a11.png)

2. 可否默认折叠与展开。比如在你的示例”Obsidian开源集团通讯录“中，我是北京分公司的，平常就只常联系北京分公司的人，其他分公司的人几乎很少联系。因此能否打开MD文件时默认只展开北京分公司的同时折叠其他分公司的。

![image](https://user-images.githubusercontent.com/20738431/218238110-c7e16b35-b9f7-4463-86ce-2a7e665e0900.png)

**Comment by LincZero** [comment]
已经完成修复，下次更新插件即可
![图片](https://user-images.githubusercontent.com/25877214/218284053-f5ded0a2-0192-433d-ae7c-853599296658.png)
