### ISSUE TITLE
chinese text on options

### ISSUE THREAD

**Issue by Andrea-28-03** [LincZero/obsidian-any-block#30]
Hi, i wanted to know if it is normal that on the options menu there is chinese and enlish text, because i don't understand chinese at all and it will be really usefull if you translate them in english; if you want if you translate them in english i could also translate them in italian 
![image](https://github.com/LincZero/obsidian-any-block/assets/62112468/7fd58b3d-43f1-4927-ab03-45b381694c43)

**Comment by nicarinai** [comment]
I also need them translated into English.

**Comment by LincZero** [comment]
cfaaebdc4fb2c17a046cd9865a0e60b8a9752182 Translated

In fact, this setting panel is mostly for query purposes, not functional purposes. It is better to use a web page for query.

A dedicated plug-in documentation website has been built and the documentation is being edited.
