### ISSUE TITLE
想问一下表格 内容太长想换行，后面的层级可以换行但是前面的层级换行就无法显示 这个该怎么解决呢 还有就是阅读模式下选择器名称没有隐藏

### ISSUE THREAD

**Issue by LDzzZ-1** [LincZero/obsidian-any-block#31]
想问一下表格 内容太长想换行，后面的层级可以换行但是前面的层级换行就无法显示
想要呈现的效果：
![image](https://github.com/LincZero/obsidian-any-block/assets/127015671/50cecfa3-f022-4926-9942-3ea321126236)
ob中呈现的效果：
![image](https://github.com/LincZero/obsidian-any-block/assets/127015671/1dbac9dd-0ee6-4500-9cb9-c6b06df3bf2c)
还有就是发现阅读视图下 选择器名称没有隐藏 实时模式下是隐藏的
![image](https://github.com/LincZero/obsidian-any-block/assets/127015671/234f242c-d03c-412f-9590-51e894a03317)

**Comment by LincZero** [comment]
试试用 `<br>` 手动换行。另外希望提供一下md的源文本给我复现一下，按道理直接换行也应该是可以的

**Comment by LDzzZ-1** [comment]
> 试试用 `<br>` 手动换行。另外希望提供一下md的源文本给我复现一下，按道理直接换行也应该是可以的

手动换行是可以的 但是直接换行是不行的
[shiyan.md](https://github.com/LincZero/obsidian-any-block/files/12496156/shiyan.md)

**Comment by PlayerMiller109** [comment]
> 阅读视图下 选择器名称没有隐藏

find a stupid way to solve.
Display view mode: Read | Edit | Source Code

![Video_2023-10-15_210819](https://github.com/LincZero/obsidian-any-block/assets/145541890/5cff118f-f1dd-4f4c-853c-249d35ef8a8f)

by using this founction in plugin setting:

![image](https://github.com/LincZero/obsidian-any-block/assets/145541890/3a083e00-d9cf-46cc-82ab-cd286b33e5ea)
![image](https://github.com/LincZero/obsidian-any-block/assets/145541890/12e24c3c-6d97-4fa3-a09c-1ae7884e3da7)

`[ ]` [] and 1 space → list2table; 
`[  ]` [] and 2 space → list2tableT.

**Comment by PlayerMiller109** [comment]
> 阅读视图下选择器名称没有隐藏

find a stupid way to solve.
Display view mode: Read | Edit | Source Code

![Video_2023-10-15_210819](https://github.com/LincZero/obsidian-any-block/assets/145541890/5cff118f-f1dd-4f4c-853c-249d35ef8a8f)

by using this function right in obsidian-any-block plugin setting:

![image](https://github.com/LincZero/obsidian-any-block/assets/145541890/3a083e00-d9cf-46cc-82ab-cd286b33e5ea)
![image](https://github.com/LincZero/obsidian-any-block/assets/145541890/12e24c3c-6d97-4fa3-a09c-1ae7884e3da7)

`[ ]` [] and 1 space → list2table; 
`[  ]` [] and 2 space → list2tableT.

**Comment by LincZero** [comment]
阅读视图下选择器名称未隐藏问题，在V3版本后，可暂时通过 `%%` 括起来 (ob的注释语法)，后面我再看有没有方法不用 `%%` 也能消除

**Comment by LincZero** [comment]
换行问题的话：

`|` 是一种语法糖，这种语法糖不支持换行 (除非要换行的内容在最后，后面没有再接 `|` 符号了)

修改：

![图片](https://github.com/user-attachments/assets/1e9d72cd-3990-48b7-a0f7-e00262a864e2)
