### ISSUE TITLE
Feature questions

### ISSUE THREAD

**Issue by mrpotatoes** [LincZero/obsidian-any-block#32]
Hey there, I have 4 questions based on the attachment.

A. Are there any options for table size or do I need to go with the `CSS` option and the heading ID ('`#`') API?

B. The short code still show in the reading view. I think this is a bug but if not is there a way to disable it from showing?

C. Is there an option/way to change or disable this text? 

D. I don't work with PDF's often so I'm not sure if this is possible. Would it be possible for the export to handle the tab bar and still be interactive?

Thanks for the help!

![Screenshot 2023-10-19 at 2 52 55 PM](https://github.com/LincZero/obsidian-any-block/assets/1066744/78ed13bb-a713-4a73-8c6a-41846a092847)

**Comment by Oddward** [comment]
I think B is indeed a bug because in live editing view (`.markdown-preview-view`) it's hidden, while in rendered view (`.markdown-rendered`) it's not

**Comment by mrpotatoes** [comment]
Thank you for the info
