### ISSUE TITLE
请教如何修改[list2table]表头改为%% [list2table] %%，这样阅读模式就不会显示了

### ISSUE THREAD

**Issue by PandaNocturne** [LincZero/obsidian-any-block#33]
请问可以直接修改源码的正则部分来修改吗，能请教一下略好
或者
%%
[list2table]
%%

我基本没啥代码基础，就想简单问一下

**Comment by LincZero** [comment]
可以的，阅读模式那个问题其实也可以回退一下版本来解决，不怎么影响。
修改正则的话，在 /src/config/abReg.ts 里，reg_header 就是这个识别头的正则

**Comment by LincZero** [comment]
可以将
```js
reg_header:   /^((\s|>\s|-\s|\*\s|\+\s)*)(\[(?!\[)(.*)\])\s*$/,
```
修改成
```js
reg_header:   /^((\s|>\s|-\s|\*\s|\+\s)*)(%%\[(?!\[)(.*)\]%%)\s*$/,
```
然后再编译，应该就可以了

**Comment by PandaNocturne** [comment]
好滴谢谢

**Comment by LincZero** [comment]
e997d523f809adb9bb2ff7cfce40f107c07c4d34

**Comment by LincZero** [comment]
dd8961f1a42703c62185dcf2fdbbcee759e70bb3

现在不用加 `%%` 也可以隐藏了
