### ISSUE TITLE
putting a note link on a line causes yellow underlines and folding of all lines below

### ISSUE THREAD

**Issue by BahneGork** [LincZero/obsidian-any-block#36]
The line with the note link disappears when i move the cursor above it, and moving it blow it folds all lines below into a single line. So lines 32-99 becomes line 32. 
![image](https://github.com/LincZero/obsidian-any-block/assets/32675320/43c3eea9-81fb-4583-a496-a8b62740ed1a)
![image](https://github.com/LincZero/obsidian-any-block/assets/32675320/0006a24a-1077-4100-be31-72d822a52730)

**Comment by LincZero** [comment]
63a93bd183b48a8e8859808b8666f3a1cff2f20a

- `[[...]]` No longer trigger，only `[...]` trigger
- `[...]` + two blank lines: no trigger
