### ISSUE TITLE
English translation of Options

### ISSUE THREAD

**Issue by gvivster** [LincZero/obsidian-any-block#37]
Hi, I like your plugin concept and would like to use it, but the Options only render in Chinese (Simplified), and I'm unable to understand them.

**Comment by LynetteCullens** [comment]
I translated it myself. To the creator, feel free to grab my fork for translation purposes. I still don't know how the mindmap works.

**Comment by LincZero** [comment]
I am very sorry for not being able to maintain it in the past year because of my busy life.

I'll have some free time next, and I will translate him.

**Comment by LincZero** [comment]
cfaaebdc4fb2c17a046cd9865a0e60b8a9752182 Translated

In fact, this setting panel is mostly for query purposes, not functional purposes. It is better to use a web page for query.

A dedicated plug-in documentation website has been built and the documentation is being edited.
