### ISSUE TITLE
README 单词拼错了

### ISSUE THREAD

**Issue by Immortal-Sty** [LincZero/obsidian-any-block#38]
今天给人推荐你插件，我说“这个插件能把列表变成思维导图”，他说“没啊，README 上没讲啊？”

然后我就发现了这个：

![图片](https://github.com/LincZero/obsidian-any-block/assets/94347641/10bd0d42-76d5-4b7f-92e3-583c4d352a61)

**Comment by LincZero** [comment]
fix: c0b282b13a562c134c750afd93627c22c5a9a6a5
