### ISSUE TITLE
[Bug] 实时预览模式无法遇览图片

### ISSUE THREAD

**Issue by Immortal-Sty** [LincZero/obsidian-any-block#4]
# 具体情况

- 插件语法用的是 `[list2tab]`；
- 图片语法用的是 Obsidian 的 Wiki 语法；
- 其它插件语法目前还没尝试；
- 只在 Obsidian 的实时预览模式有问题；
- Code 如下：
	```markdown
	[list2tab]
	- 表格
	  - ……
	- 思维导图
	  - ……
	- 图片
	  - ![[attachments/测试 2023.02.14-1.jpg]]
	```
- 结果如下图：
	![](https://s3.bmp.ovh/imgs/2023/02/14/4c044d9454556e90.png)

**Comment by LincZero** [comment]
这是官方的bug，官方api的 `MarkdownRenderer.renderMarkdown` 接口存在问题，23年11月底才有人修复了该bug，提出了新的api

参考：
https://github.com/obsidianmd/obsidian-api/issues/120
https://github.com/marcusolsson/obsidian-projects/issues/427
https://github.com/marcusolsson/obsidian-projects/pull/742

**Comment by LincZero** [comment]
近期才有空更新插件，把这个给修了，下版本过几天再发

653e6109df8be088ce229cdefd23542af38d3a5a
