### ISSUE TITLE
作者我爱你, 反馈一个问题么么么💋💋💋💋

### ISSUE THREAD

**Issue by Dev-MOBAI** [LincZero/obsidian-any-block#41]
列表中含有公式块的话, list2mermaid和list2mermaid就无法正常显示. 然后如果list2pumlMindmap的话, 列表中的公式不会渲染出来, 还是纯文本格式, 希望作者修复爱你么么么么么么么么么么💋💋💋💋💋💋💋

**Comment by LincZero** [comment]
- list2mermaid 是 mermaid 提供的
- list2pumlMindmap 是 plantuml 提供的
- list2markmap 是 markmap 提供的

前两者都不支持嵌入md格式，第三个实测是支持的：

![图片](https://github.com/user-attachments/assets/29380fb9-a410-46f8-96ca-f9ea6b3e4cba)

只是记得过于复杂的公式会出现bug

1. 可以的话你尝试在 [markmap官网](https://markmap.js.org/) 尝试一下你的公式他是否能够支持，或者查看obsidian的其他markmap插件是否支持。如果他们支持但我这边不支持，我再看看可能是什么bug。如果都不支持，尝试将公式换下写法试试
2. 依然无法解决的话，希望提供一下失效的公式
