### ISSUE TITLE
相关链接404

### ISSUE THREAD

**Issue by chenbihao** [LincZero/obsidian-any-block#42]
![image](https://github.com/user-attachments/assets/b3c3913c-cb93-4b13-94a1-a036195bebcb)

en
Related links：tutorial、use skill、contribution、secondary development
[Online Wiki - github.io](https://linczero.github.io/MdNote_Public/%E4%BA%A7%E5%93%81%E6%96%87%E6%A1%A3/AnyBlock/)
[Online Effects warrior - github.io](https://linczero.github.io/MdNote_Public/%E4%BA%A7%E5%93%81%E6%96%87%E6%A1%A3/AnyBlock/README.show.md)
zh
相关链接：教程、使用技能、贡献、二次开发
[在线文档 - github.io](https://linczero.github.io/MdNote_Public/%E4%BA%A7%E5%93%81%E6%96%87%E6%A1%A3/AnyBlock/)
[在线效果展示 - github.io](https://linczero.github.io/MdNote_Public/%E4%BA%A7%E5%93%81%E6%96%87%E6%A1%A3/AnyBlock/README.show.md)

**Comment by LincZero** [comment]
好，解决了

0bdde04da7d418d6d2bcd2f707ca528835083dd2
