### ISSUE TITLE
[Feat] 未提供的标题选择器和mdit `:::` 选择器在阅读模式下的支持

### ISSUE THREAD

**Issue by LincZero** [LincZero/obsidian-any-block#44]
相较于另外四个选择器（代码块/引用块/列表/表格），这两个在阅读模式下的实现更麻烦的（不是难，就是麻烦）

会做的，但可能要两三个版本更新的周期

**Comment by calmwaves111** [comment]
期待😉

**Comment by LincZero** [comment]
a294bb015f1800d7882ac20fb9fa54517f1293e7

已提供，发布后关闭

**Comment by calmwaves111** [comment]
好像是有些问题
下面是在3.0.6中的效果，左边是纯文本，右边是在ob的实时预览下，ob的阅读模式下是不生效的
![image](https://github.com/user-attachments/assets/f6b973fb-59a8-4a11-b23b-4f986cd94883)

升级到3.1.0后 实时预览下也没效果了，阅读模式也不变化，而且编辑的时候有卡卡的感觉，有时候还会吞掉一些字符 
![image](https://github.com/user-attachments/assets/cdea4d49-e4a2-4cda-a16b-00e698c62da7)
![image](https://github.com/user-attachments/assets/e2042b3b-071e-4096-9c88-80bd160a90c4)

**Comment by LincZero** [comment]
title2code是自定义的吧……

**Comment by LincZero** [comment]
## 阅读模式不生效的问题

需要清除阅读模式的缓存：关闭标签页重新打开即可

原因：
切换到阅读模式的对的，但是当打开过一次阅读模式后，ob会缓存一遍页面。
此时如果切换回源码/实时模式编辑内容，编辑完后再切换回阅读模式，ob不会去识别未经改动的部分，而是只看分析变动的部分。此时会导致AnyBlock识别异常。

## 卡顿问题

可能是新的别名系统导致的，我看看怎么优化下。相关进展到新issue #48

**Comment by LincZero** [comment]
我傻了，有时可以有时不行，每次debug时他又突然可以用了。然后某个时间点又莫名其妙不能用了

明天好好检查一下

**Comment by calmwaves111** [comment]
现在是3.1.1，好像出现了别的问题

![image](https://github.com/user-attachments/assets/a6542f8f-410c-45ab-99b5-b42a2a6f6c6f)

**Comment by LincZero** [comment]
3.1.2 修了，避免问题还存在，过几天再关闭这个issue

**Comment by calmwaves111** [comment]
![image](https://github.com/user-attachments/assets/9831c42c-6247-493d-8c41-3594186af19f)

我这边是完美了，现在是这样写的 `[title|quote|add(> [!note])]`

但是像title2quote，或者code2quote是用不了的

**Comment by LincZero** [comment]
我不记得插件有 title2quote 和 code2quote 命令啊

你可以用 `[quote]` 和 `[X|quote]` 来代替

如果你喜欢用你自己的命名，那就在别名系统里注册，让 [title2quote] 等同于 [quote]
