### ISSUE TITLE
你好开发者, 我遇到了一个问题

### ISSUE THREAD

**Issue by Dev-MOBAI** [LincZero/obsidian-any-block#45]
你好开发者, 我发现[list2mermaid]块中的内容中只要含有空格或者中文符号(如，), [list2mermaid]块就会无法显示

**Comment by LincZero** [comment]
## anyblock是如何把列表转化为mermaid的

如

```md
- 这，是一段内容
  - 这。是另一段内容
```

会转化为

````md
```mermaid
graph LR
这，是一段内容 --> 这。是另一段内容
```
````

所以总的来说，不能脱离mermaid的语法范畴。mermaid并不允许节点名使用非法字符作为节点名

## 如何解决？

一是使用mermaid的节点别名。例如这样：

```md
- A[这，是一段内容]
  - B(这。是另一段内容)
    - A
```

就会转化为：

````
```mermaid
graph LR
A[这，是一段内容] --> B(这。是另一段内容)
B-->A
```
````

即：

```mermaid
graph LR
A[这，是一段内容] --> B(这。是另一段内容)
B-->A
```

二是使用对语法要求没那么高的其他处理器，如 `list2pumlMindmap`、`list2markmap`

**Comment by Dev-MOBAI** [comment]
> ## anyblock是如何把列表转化为mermaid的
> 
> 如
> 
> ```
> - 这，是一段内容
>   - 这。是另一段内容
> ```
> 
> 会转化为
> 
> ```
> ```mermaid
> graph LR
> 这，是一段内容 --> 这。是另一段内容
> ```
> ```
> 
> 所以总的来说，不能脱离mermaid的语法范畴。 mermaid并不允许节点名使用非法字符作为节点名
> ## 如何解决？
> 
> 一是使用mermaid的节点别名。 例如这样：
> 
> ```
> - A[这，是一段内容]
>   - B(这。是另一段内容)
>     - A
> ```
> 
> 就会转化为：
> 
> ```
> ```mermaid
> graph LR
> A[这，是一段内容] --> B(这。是另一段内容)
> B-->A
> ```
> ```
> 
> 即：
> 
> ```mermaid
> graph LR
> A[这，是一段内容] --> B(这。是另一段内容)
> B-->A
> ```
> 
> 二是使用对语法要求没那么高的其他处理器，如 `list2pumlMindmap`、`list2markmap`

好的好的开发者, 爱你么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么
