### ISSUE TITLE
list2markmap不展示

### ISSUE THREAD

**Issue by zhihancn** [LincZero/obsidian-any-block#46]
作者大大您好，本人使用过程中遇到一点BUG

插件版本：3.0.4

使用案例[链接](https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/README.show.html#to-markmap-%E8%BD%ACmarkmap%E6%80%9D%E7%BB%B4%E5%AF%BC%E5%9B%BE)时。无法生成对应图。

源码：
<img width="748" alt="image" src="https://github.com/user-attachments/assets/3d67d82f-bde4-42fa-a004-58a4a83c1240">

编辑模式下展示

<img width="748" alt="image" src="https://github.com/user-attachments/assets/c6e0a05f-cbcb-4296-a030-7597838a10a3">

阅读模式下展示

<img width="858" alt="image" src="https://github.com/user-attachments/assets/366ecc0b-6e49-45b5-a538-5e07a4083561">

在各个模式之下均已点击过多次 **ReReRender MarkMap**

是否会与其他插件冲突，如：mindmap nextgen？

**Comment by LincZero** [comment]
把ob的所有标签页关闭，然后重启ob看看。

这两个插件是不冲突的，至于其他插件不知道。冲突问题目前据我所知，只有和表格类的extend可能有一点

**Comment by LincZero** [comment]
![图片](https://github.com/user-attachments/assets/7aba9472-882f-466c-9e64-c2147bc4db96)

**Comment by zhihancn** [comment]
可以，关闭tab页重开后实测解决。虽然我有加载sheet extend插件，但是似乎不影响markmap转换。感谢作者大大
