### ISSUE TITLE
[BUG] 可否当非md代码块时不进行渲染？

### ISSUE THREAD

**Issue by chenbihao** [LincZero/obsidian-any-block#47]
## 遇到了bug：

当正常写一些代码时，如果正文首行有 `[*]` ，会错误渲染，并且影响到整篇笔记

例如这里会把ini的代码块，错误当做md去渲染，
并且命中了字符串 `[*****]` 进行渲染，还会影响到非本代码块的后续所有内容

## 期望：

当只有代码块标注为md时，并且标识完全命中时（白名单机制，而不是正则模糊匹配），才进行渲染

## 现状

- 无论代码块标注为任何类型，
- 并且当代码块正文首行为`[]` 并且中间有文本时
- 并且当代码块正文有`#`时 （目前暂时发现井号会触发，其他md标识未测试）
会错误渲染后续所有的内容

![image](https://github.com/user-attachments/assets/14602cbb-4d72-4540-bf2e-895c9385c78d)

### mysql

```ini
[mysql]
# 设置mysql客户端默认字符集
default-character-set=utf8mb4

# 其他代码省略... 这是一个很普通的mysql配置文件

```

### MariaDB

```shell
# win 版本
docker run -p 3307:3306 --name mariadb --restart=always -itd mariadb:latest
```

**Comment by LincZero** [comment]
#18
ecaa54d3dfac0ac71889268cf922e402b35e86d0

test

![图片](https://github.com/user-attachments/assets/7a59b2e3-5bb7-4b94-8659-3f977ea4e2a6)

**Comment by LincZero** [comment]
[3.0.7-beta](https://github.com/LincZero/obsidian-any-block/releases/tag/3.0.7-beta)

该版本未完善未正式发布到社区商店，给你编译个beta版本，需手动下载安装
