### ISSUE TITLE
希望注释能放到文档属性里，不然会污染笔记的

### ISSUE THREAD

**Issue by x2o2** [LincZero/obsidian-any-block#49]
希望注释能放到文档属性里，不然老感觉有一些奇奇怪怪的东西

[title2list]
- 1
    - 2
        - 3
    - 4
- 1
    - 2
        - 3
    - 4

如果能把[title2list]改到文档属性就好了。
比如只作用第一个，那么在文档属性里添加一条anyBlock : title2list:nth-of-type(1)

比如不作用第一个，那么在文档属性里添加一条anyBlock : title2list:not(:nth-child(2))

排除标题为xxx内的，  anyBlock : title2list:not(#xxx)
只作用标题为xxx内的：
> 完全匹配：anyBlock :title2list:[title*="xxx"]
>包含：anyBlock :title2list:[title^="xxx"]
> 以 "xxx" 结尾：anyBlock :title2list:[title$="xxx"]

**Comment by LincZero** [comment]
我知道你想说的大概是什么效果，类似一些主题或插件的功能，但感觉这种方式更适用用全局生效。

如果不是全局生效而是在元数据里选择单独的某一个块……怎么说呢。有点别扭、并且对于场景里有多个AB块的时候反而混乱，也不能排除掉文档污染。

下面是目前对于文档污染的一些已有的解决方法，先看一下能不能帮助到你

## 一是利用别名系统

例如你定义一个别名

`/\目录:$/` --> `list2dt`

```
[这是一个Linux的etc目录:]

- xxxxx
  - xxxx
```

自然语言代替指令看起来会好一点

## 二是利用ob注释

默认的头部正则：`/^((\s|>\s|-\s|\*\s|\+\s)*)(%%)?(\[((?!toc)(?!TOC)[0-9a-zA-Z\u4e00-\u9fa5].*)\]):?(%%)?\s*$/,`

一般插件存在的时候，头部指令是不显示出来的。如果想要让插件在关闭后的效果好看一些，可以使用 `%%` 将 `[xxx]` 包裹起来

这样在插件关闭后，选择器头部也就不显示了。但缺点是仅限在支持 `%%` 注释的ob能这样做，迁移到其他软件/平台需要额外插件来隐藏 `%%` 内的内容

## 三是修改配置文件 (需编译)

我将匹配规则放在了 ABReg.ts 文件中，哪怕没ob插件代码基础的也可以轻松修改匹配方式并和编译。

例如将 `[]` 去掉换成更宽松的表示方法：

```
现在我们来看一下三国时期重要的事件时间线吧：

- xxx年
  ......
- xxxx年
  ......
```

将匹配规则改得足够宽松，加上别名系统，就能看上去完全没有入侵痕迹……只要不怕误选……

**Comment by x2o2** [comment]
看到列表转表格我才来的，因目前没发现有一个是能把列表转表格、转目录树 进行观看的。
仔细看了后，你这列表转表格是额外的小功能😂

**Comment by LincZero** [comment]
## 插件文档

1. 初步使用，就是单纯使用各种处理器。可以看Github上的 “在线展示” / "在线文档"，https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/README.show.html
2. 深入使用，利用灵活的选择器，可以搭配其他平台语法和其他插件，可以参考 https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/docs/zh/03.%20%E9%80%89%E6%8B%A9%E5%99%A8.html

各种花里胡哨的处理器并不是插件的核心，看插件名就知道，插件开发的初衷和核心应该是选择整篇md笔记中的任意一部分范围（这是其他插件做不到的，独属于AnyBlock的特点和优势。只不过大部分人只用到了我顺带做以及用于引流的第一点……）

## 没有固定用法，举两个用例

例如搭配其他其他插件，作为其他插件的补强（见图片中的第三种用法）

![图片](https://github.com/user-attachments/assets/ce608043-dac2-41d4-8d33-4a8d6b60c531)

再例如论坛里一名用户开发的奇怪用法（这个我开发的时候是真没想到还能这样用）：

https://forum-zh.obsidian.md/t/topic/39261

总之核心是 “任意选择一段范围，并进行任意处理” 外，除此之外没有什么制约……

**Comment by PlayerMiller109** [comment]
>全局生效

全局的话要不试试 CSS [无序 - 表格化阅览](https://pkmer.cn/Pkmer-Docs/10-obsidian/obsidian%E5%A4%96%E8%A7%82/css-%E7%89%87%E6%AE%B5/obsidian-%E6%A0%B7%E5%BC%8F-%E6%97%A0%E5%BA%8F%E5%88%97%E8%A1%A8%E7%BE%8E%E5%8C%9620%E7%89%88%E6%9C%AC/#1css-%E6%9D%A5%E6%BA%90) 呢？不过我没有用，有问题可以问原作者哈。

**Comment by LincZero** [comment]
感觉和插件定位不是太符合，插件不是用于作用全局的，关闭此issue
