### ISSUE TITLE
[bug]Syntax error in graph  mermaid version 9.3.0

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [LincZero/obsidian-any-block#5]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/71814666/218730386-a7296266-185e-40cb-9db6-efdfc5258c4d.png">

列表转mermaid思维导图会出现上图问题

**Comment by LincZero** [comment]
看看源md

**Comment by shoudeyunkaijianyueming** [comment]
[04002民法的性质.md](https://github.com/LincZero/obsidian-any-block/files/10740162/04002.md)

**Comment by LincZero** [comment]
顿号在mermaid的流程图里是非法字符……mermaid流程图的非法字符是真滴多
这可能需要一个更强的、能够支持md语法的流程图库，例如markmap.js（我没有内置，但以后版本可能会想办法通过外部插件使用一下）

**Comment by shoudeyunkaijianyueming** [comment]
好的谢谢
