### ISSUE TITLE
希望能改善瀑布流和其他卡片相关的样式

### ISSUE THREAD

**Issue by dolores824** [LincZero/obsidian-any-block#50]
感谢作者大大出的这款插件，太好用了！看到更新了新的转换器样式，马上试用了很期待的卡片样式，似乎目前的样子跟主题有点割裂

<img src="https://github.com/user-attachments/assets/d48b0e8b-721a-4b06-bb5a-3a0ce8791ceb" width="500">
 <br><br>

不知能否实现像[mcl](https://efemkay.github.io/obsidian-modular-css-layout/multi-column/07-list-card/)或者minimal主题里的[cards](https://minimal.guide/cards)那样跟主题更融合的样式呢，感谢！

![image](https://github.com/user-attachments/assets/22bcb68e-09ba-442e-9fbd-c9187f8a4d64)

**Comment by LincZero** [comment]
现在确实有些丑，然后后续我会慢慢改良（精力有限，样式我本来打算没人提就放后一些做的）

现在都是按默认主题和黑夜模式来匹配

这里提供临时解决方法：

- 如果想要无背景色，像你发的图二那样，则添加css片段：`.ab-items-item {background: none;}`
- 如果想要自定义背景色，添加：`.ab-items-item {background-color: #f8f5f2;}` // 替换成你想要的颜色
- 如果想像图二那样分三栏，则将 `[list2card]` 修改为 `[list2card|addClass(ab-col3)]`
- 如果想像图二那样增加卡片圆角和title下的横线，用也都同理，用css就可以做

**Comment by dolores824** [comment]
感谢！我鼓捣下css
