### ISSUE TITLE
更新3.1.1后，2lt不可用了

### ISSUE THREAD

**Issue by hsingll** [LincZero/obsidian-any-block#51]
教程网站的示例也一样挂了，不显示折叠表格样式
<img width="1440" alt="Snipaste_2024-08-29_16-30-40" src="https://github.com/user-attachments/assets/28f3ab60-6911-449a-bf2e-b5b7237f07b2">

**Comment by LincZero** [comment]
为了避免旧用户受影响，3.1.2会调整回来。

另外借楼补充：

1. 如需要紧急修复，可自行解决：打开插件文件夹/any-block/data.json，在 `"alias_user": [...]` 中插入别名，如：
  ```json
  "alias_user": [
    {"regex": "|list 140lne|2lt|", "replacement": "|list2lt|"},
    {"regex": "|title 140lne|2lt|", "replacement": "|title2list|list2lt|"},
  ]
  ```
2. 新版本可以重构了别名模块，并模块化，允许使用任意指令代替任意指令。可以使用更简短的表示、或使用中文指令代替。也允许使用正则来设置，如识别 `...表` 等
