### ISSUE TITLE
tab无法实现！

### ISSUE THREAD

**Issue by Peingxious** [LincZero/obsidian-any-block#55]
[list2mdtab] 还是[list2tab]？
我看了旧版本和新版本的doc都不行，说明上的也是直接显示列表，不是显示tab

**Comment by LincZero** [comment]
list2tab/list2tabs/tab/tabs/标签/标签页，都行

如果还是不行，请告知你所用的ob和anyblock版本

**Comment by LincZero** [comment]
https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/README.show.html#tabs-%E6%A0%87%E7%AD%BE%E9%A1%B5

这里官网显示不出来，是因为因为我官网用的AnyBlock版本还是3.1.0版本，没有更新。3.1.0的重构了别名模块，一些别名似乎有缺失

**Comment by Peingxious** [comment]
我用的电脑版，最新版本的v1.7.1,插件用的是3.1.2
我在网页上也没有看到展示效果，我是在git上下载的
![image](https://github.com/user-attachments/assets/25bf52d9-2c08-4592-80fb-a73fc1568db1)
我试了标签，没看出来效果🥲

**Comment by LincZero** [comment]
我知道了，这个东西是我在发布 3.1.2 当天修复的，3.1.2并没有修：

![图片](https://github.com/user-attachments/assets/9bd46bb3-7dd3-4ae1-8255-5f62e4f4f3de)

1. 你可以github下载 3.1.3-beta
2. 你也可以在当前版本使用 [tab] 或 [tabs] 代替 [list2tab]
    (3.1.0后更建议方案2，会自动根据下面是list还是title自动选择是list2tab还是title2tab)

**Comment by Peingxious** [comment]
好的，你关闭太快了。效率真高！

**Comment by Peingxious** [comment]
测试了，可以用了！
需要删除3.1.2,包括所有的data，然后重新下载，再替换了，就可以实现了。
