### ISSUE TITLE
3.1.1 ![]嵌入的anyblock无法渲染(切换编辑模式或重开页面又可以)

### ISSUE THREAD

**Issue by DZL1943** [LincZero/obsidian-any-block#57]
<img width="1023" alt="图片" src="https://github.com/user-attachments/assets/9aeae943-8538-4351-88d0-1af446bbe08a">

**Comment by LincZero** [comment]
之前发在
#56
现在怎么重开了一个issue……我把这个关了，还是在那边讨论。

另外我需要源md才能复现这个问题，不然复现不出来
