### ISSUE TITLE
list2markmap 重复渲染且重叠

### ISSUE THREAD

**Issue by maxming2333** [LincZero/obsidian-any-block#58]
**机型：** MacOS
**Obsidian 版本：** 1.6.7

------------

新创建一个空白仓库，使用的 demo 测试

```
[list2markmap]

- Links
  - [Website](https://markmap.js.org/)
  - [GitHub](https://github.com/gera2ld/markmap)
- Related Projects
  - [coc-markmap](https://github.com/gera2ld/coc-markmap) for Neovim
  - [markmap-vscode](https://marketplace.visualstudio.com/items?itemName=gera2ld.markmap-vscode) for VSCode
  - [eaf-markmap](https://github.com/emacs-eaf/eaf-markmap) for Emacs
- Features
  - Lists
    - **strong** ~~del~~ *italic* ==highlight==
    - `inline code`
    - [x] checkbox
    - Katex: \$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$ <\!-- markmap: fold -->
    - \[More Katex Examples](#?d=gist:af76a4c245b302206b16aec503dbe07b:katex.md)
    - Now we can wrap very very very very long text based on `maxWidth` option
  - Blocks
  - 
    ```javascript
    console.log("hello, JavaScript")
    ```
  - | Products | Price |
    |-|-|
    | Apple | 4 |
    | Banana | 2 |
  - ![](https://markmap.js.org/favicon.png)
```

<img width="847" alt="image" src="https://github.com/user-attachments/assets/db512e9f-1386-4174-bdf7-48522437c792">

但是 预览模式 或者 编辑模式（非源码模式），显示出来的 markmap 就是重叠一堆

<img width="853" alt="image" src="https://github.com/user-attachments/assets/9e21dbf2-b413-48b5-9bc7-ca95a2a01435">

并且点击刷新按钮，历史的一样无法去除，又生成了一个新的覆盖上去


------------

另外一个问题：第一次预览，渲染出来是空白，反复切换预览模式，才有可能出现

<img width="1885" alt="image" src="https://github.com/user-attachments/assets/e8883be9-c5e5-406d-92ae-655080e95cf3">

**Comment by LincZero** [comment]
下版本更新后正常

**Comment by LincZero** [comment]
另外提供另一种使用方法：

1. 安装插件 markmap nexgen，检查其能正常使用
2. 将anyblock第一行的 `[list2markmap]` 替换成 `code(markmap)`

该方法中，anyblock将负责选择范围，然后交由给 markmap nexgen 插件进行渲染

**Comment by maxming2333** [comment]
`markmap nexgen` 移动端无法显示，然后他那个插件好像还有点问题

以下是我解决此问题的 PR https://github.com/LincZero/obsidian-any-block/pull/59

**Comment by maxming2333** [comment]
不过这里发现，反复点击刷新按钮，有时候会多个 markmap 从有显示，突然就都变成空白了

**Comment by LincZero** [comment]
## 感谢贡献

其实更鼓励去修 markmap nextgen，那个其实我也发现有一些bug。
包括第一次安装启用可能要清缓存，内置的markmap版本较旧不支持注释默认折叠，还有你说的bug等。

然后我的插件应该去二次调用他们那些插件，即能模块化方便维护，又能减少我插件的体积（本来就200KB不到，内置mermaid、markmap、plantuml等直接变9MB了……）

## 初始空白没渲染的问题

其中也有一些 markmap bug 是我这里有的但他那里没有的，包括你说的空白页的bug：

> 你将页面内容塞得足够满，然后markmap图放头部，刚开始是正常的，但往下滚一段距离再回去后，markmap没有被自动显示。markmap nextgen版本无该问题。
> 原因：我只监听了一些打开新页面的事件。往下滑再往上滑时，ob将不显示的内容缓存起来，然后再放出来。这个过程我没有监听到。
> 
> 可能的修复方法：最简单的莫过于监听页面滚动事件，每滚200px调一下我那个ABConvertEvent。更原理性地检测是去检测他的有个visiableRange，那个东西变化时调函数。

但主要不太想重复造轮子，不太想在我这里修，想去修 markmap nextgen 后直接用他的。但最近没啥时间去熟悉别人的代码

**Comment by LincZero** [comment]
## ob缓存导致无法获取div重新被载入的事件

具体问题描述看上一层。当然，我相信这个事件应该是有的，如果能捕获这个事件可以解决该bug。

但这种方式短时间无法修复，所以我提供了另一种有点绕圈子的实现

## “模拟代码块” 来自动刷新 - 原理

ad30b223fc82fd68b254b3a169289d0a781f98c7

markmap nextgen 之所以不受缓存重载的问题，是因为使用的 registerMarkdownCodeBlockProcessor 是官方api提供的，ob缓存重新加载时会自动触发对应的回调函数。

那么我如果假装这个部分是个代码块，应该就能自动刷新了。“模拟代码块” 的功能我前面提到过：

> 将anyblock第一行的 [list2markmap] 替换成 [code(markmap)]

但是这里是转化成代码块后让其他插件进行处理，而现在我们将流程稍微修改一下，变成 “转化为代码块后让AnyBlock” 继续处理，就可以了

## “模拟代码块” 来自动刷新 - 操作

![图片](https://github.com/user-attachments/assets/11f1fbdb-f1c1-4b44-b354-bfdf7d16ef5a)

`[add([list2markmap])|code(ab)]` 这里串联了两个处理器，第一个在文本开头添加一行 `[list2markmap]`，第二个处理器则使用一个代码块将内容包括起来，并将代码类型修改成 `ab` (ab/anyblock都行)

然后渲染结果就是一个完美自动刷新的 list2markmap 了！

## 补充，优化书写

如果认为 `[add([list2markmap])|code(ab)]` 太长，我们可以使用 AnyBlock 的 ”别名模块“，用更短的标识来表示这一串东西，例如用 `[map]` 表示这一长串

**Comment by LincZero** [comment]
9636b090f1ea1ceb23f49312725732e81f8f1238

之前想岔了，将abConvertEvent的三个事件搞混了。另外两个事件要等css加载到自身div才能调用，但markmap那个不需要。

后面版本正常使用 `[markmap]` 就可以了
