### ISSUE TITLE
[BUG] 在实时预览模式下`- [ ]`被错误识别为选择器，导致意外渲染

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#6]
任务列表符号`- [ ]`在实时预览模式下被错误识别为选择器，导致意外渲染。在阅读模式和源码模式未发现此问题。

测试环境：
- Windows 11 22H2
- Obsidian 1.1.9 沙箱仓库中仅安装Any Block插件1.3.1

![image](https://user-images.githubusercontent.com/20738431/219022164-ee62b812-1424-4db2-bf12-7a24eafd3646.png)

**Comment by LincZero** [comment]
这个我也发现了，原因：`reg_header: /^\s*(-\s)*\[(.*)\]/`

两种解决方式
1. 去除掉正则中的(-\s)，只让选择器在根部，能超简单的就修复好了
2. 继续我原来的想法：让选择器不止在文档根部生效，在引用块或列表块内生效。这难很多
（这个选择器的增强优化还没做出来，但我忘了将header的正则给去除了，就导致了这个bug）


还是选择第二种方式吧，难度较高，所以这个会较晚才会修复。但目前在TODO的第一优先级
