### ISSUE TITLE
这么多用户难道就我蠢？

### ISSUE THREAD

**Issue by alexguo78** [LincZero/obsidian-any-block#60]
1.开发的功能似乎很好，但并不能让人马上使用起来
2.网上教程一顿搜，gpt一顿问，再结合哥们你的教程截图我特么才总结出来要使用[list2table]，算我蠢
3.类似[list2table]格式有哪些？对应什么效果？截图搞了一大堆作者是截嗨了。我照做了没效果是为啥也不给几个代码例子。
4.感觉作者的使用教程主要在展示效果，并没有多少对用户有用的，跑题严重。

**Comment by LincZero** [comment]
里面有在线网站，包含在线教程 在线渲染 和一些其他细节。
在里面切换标签页就能看到各种图对应的源代码了

**Comment by LincZero** [comment]
见：https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/README.show.html

**Comment by alexguo78** [comment]
感谢大哥提供教程，打开页面首先看到“Effects warrior (效果展示)”，然后找对应的代码，结果没找到代码，开始怀疑自己就我瞎吗？因为不太相信能写出这么好功能的人交代不清楚怎么用？
