### ISSUE TITLE
[Docs] 如何自定义AnyBlock渲染的高亮色或其他颜色

### ISSUE THREAD

**Issue by jotithan425** [LincZero/obsidian-any-block#61]
更新完插件，颜色好像不能正常显示了，换回了原来的3.1.2的css就能正常显示了。下图为3.1.4的渲染
![image](https://github.com/user-attachments/assets/ffd7e33d-3503-4b35-a831-6d64aa7d1fc7)

**Comment by LincZero** [comment]
3.1.4 为了适应明暗模式+不同的主题，“高亮线” 统一使用 `--blockquote-border-color` 属性（这个颜色等同于引用块左边的颜色，在不同的主题这个颜色不同，一般也是这个主题的主题色）

下面是举例：（上中下是三个不同的主题，左中右是三个不同的场景）

![图片](https://github.com/user-attachments/assets/dfc56fe8-33c7-4085-ab3e-5bcc17a3eeff)

除了 timeline 外，其他的AnyBlock的 “高亮线”，例如图右的卡片处理器，也都是采用与主题统一的色调

**Comment by jotithan425** [comment]
懂了，能在插件设置中，给个选择吗。挺喜欢原来的颜色的，不然要去style setting里面全局修改了

**Comment by LincZero** [comment]
如何 DIY？

1. 可以直接修改 `--blockquote-border-color`
2. 如果只修改AnyBlock的高亮色，则可以修改 `--ab-bright-color`

修改方法：

1. 设置 > 外观 > 划到底 > CSS代码片段 > 右侧有个文件夹图标 > 点击打开对应的文件夹。
2. 在里面创建 `修改主题色.css` 文件，添加下面内容被保存
   ```css
   --blockquote-border-color: #ff0000;
   ```
3. 回到设置面板的CSS代码片段 > 刷新 > 启用刚刚添加的片段

**Comment by jotithan425** [comment]
好的，非常感谢！

**Comment by jotithan425** [comment]
顺便还有一个问题，有任何办法单独导出渲染的片段为图片吗，只能在ob里面看到渲染图。各种格式导出，不能渲染出来。除了一个share note可以正常预览
