### ISSUE TITLE
Cards格式和渲染（？）的问题

### ISSUE THREAD

**Issue by dolores824** [LincZero/obsidian-any-block#64]
关于标题转卡片，似乎转成卡片后，原来的标题会被渲染（？）成普通的`p`
因此能否标题转卡片能像列表转卡片那样，保留原来的标题样式呢

![屏幕截图 2024-09-26 101027](https://github.com/user-attachments/assets/40322422-efe4-4404-9244-f908bec6fbde)
![屏幕截图 2024-09-26 100956](https://github.com/user-attachments/assets/3311428d-f90f-418d-88e9-2ad04446ec78)
![屏幕截图 2024-09-26 101012](https://github.com/user-attachments/assets/1c7b9bc8-4a66-4b22-98a1-1f151753951b)
![屏幕截图 2024-09-26 101211_mark](https://github.com/user-attachments/assets/ad5b8c15-93c8-40cd-8e8e-186c2adf0809)
   
   
   
   
关于list2card，想问下每个list下面的内容，能否不加额外空格就能被识别成卡片内容？

列表下面的内容不加空格，无法识别
![image](https://github.com/user-attachments/assets/e2c10414-d722-4e07-b4ad-1ec277ac85a1)
加了空格
![image](https://github.com/user-attachments/assets/66301d37-ff7c-4a67-8b4d-63c565f37132)

**Comment by LincZero** [comment]
## title2card 保留标题

想了些能达到类似效果的做法：

### (1) 标题后面再添加标题

![图片](https://github.com/user-attachments/assets/27e088ac-26fb-4561-8d6c-35420c7c8564)

### (2) 添加自定义样式

![图片](https://github.com/user-attachments/assets/63532581-0fae-448b-9e0d-2dcef1d18b8d)

### (3) 直接修改自定义样式

如果想让标题呈现标题的样式，直接修改 `.ab-items-title` 就好

### 补充

感觉上不应该做将标题层级保留下来，并将ab-items-title设置成对应的标题。因为这会导致：你在不同的标题层级下使用card处理器时，卡片盒的样式都不一样。例如你在同一篇文章有个卡片在heading1下面，有个卡片在heading4下面，那么两个卡片就会长得不一样。此时大概又有人提issue说能不能让这些卡片渲染起来长得一样

**Comment by LincZero** [comment]
## 关于列表不加缩进空格的问题

那我就没办法判断选择器要什么时候结束啊，那列表选择器就会从开始声明一直选择到文章末尾为止

如果不想加那么多缩进，可以用mdit的 `:::` 头尾选择器，也比较灵活。详见AnyBlock文档的 “选择器.md”
