### ISSUE TITLE
表格线条不明显、不可设置

### ISSUE THREAD

**Issue by tomato878** [LincZero/obsidian-any-block#67]
在生成的表格中，很多表格框线不明显。希望增加对于边界线等线条的颜色、透明度设置。

**Comment by LincZero** [comment]
生成的表格颜色和你直接用md画出来的表格颜色难道不是一样的吗？

**Comment by tomato878** [comment]
> 生成的表格颜色和你直接用md画出来的表格颜色难道不是一样的吗？

一样，但我使用了表格美化的css进行修改了。但css对于插件any block无效。所以，希望能增加该功能。因为一些表格线条实在是太暗淡，而且无法进行美化。

**Comment by LincZero** [comment]
CSS修改肯定是有效的，都是同理的。

可能是你CSS选择器的级别不够，像这样多套几个选择器 `.ab-note table.ab-table td, .ab-note table.ab-table th {}`，或者加个 `!important` 试试

838b5060bd6d85e3a549ca890d17d31e0840c440
刚改了一点。后续修改应该只要修改ob的 `--ab-table-border-color` 变量就行了

**Comment by LincZero** [comment]
#62 当前没解决，但今天刚好找点一些实现思路
