### ISSUE TITLE
标题里带了空格就不能跳转至原文件以及dataview显示的问题

### ISSUE THREAD

**Issue by laogao2005** [LincZero/obsidian-any-block#68]
我太喜欢[tabs]了，因为可以大大节约页面长度，条例清晰，使用中发现了些问题：
①标题里带了空格，就不能跳转至原文件，如图
![问题11](https://github.com/user-attachments/assets/5b31af78-a599-4f6f-98c1-12864490921d)

把空格改为连词符，就没有问题了
![问题22](https://github.com/user-attachments/assets/393434c8-96ec-41fa-adce-20549799e39d)

②dataview显示的问题，如图在阅读视图显示不正常，在编码视图是正常的

![问题33](https://github.com/user-attachments/assets/7f114d94-a7f9-450a-98a2-2a3e78bfb18c)

以下，是我的代码

````
[tabs]
- 🤔 快速导航
 [卡片]
  -  `button-richeng`
  -  `button-kanban`
  -  `button-suibi2`
  -  `button-renwu2`	
- 😏 时间飞快
 [卡片]
   - 今天还剩 `= round((date(tomorrow)-date(now)).hours,2)` 小时
   - 这周还剩 `= round((date(eow)-date(now)).day,2)` 天
   - `= date(today).month` 月还剩 `= round((date(eom)-date(now)).day,2) ` 天
   - 今年还剩`= round((date(eoy)-date(now)).day,2)`
- 🤩 帮助教程
 [card]
   - 🚩 [[分栏效果示例|分栏示例]]
   - 🥑 [[Blue-Topaz-Themes-Tips|BT tip]]
   - 💾 [[77-Example|示例库]]
   -  🪄[[示例库内置的插件列表|插件列表]]

```

**Comment by LincZero** [comment]
## 链接带空格问题

问题一估计应该改成 `![这是带 空 格 的链接](这是带％20空％20格％20的链接)` 或 `[[这是带 空 格 的链接|这是带％20空％20格％20的链接]]` 这种？或者在两边加 `<>` 符号
你先试下，链接带空格会有兼容性。因为url本来就是要%20代替空格。

虽然我这边可能也能转义一下处理，但按责任划分，这类问题可能应该让官方修好一些。这类问题应该不只我插件有

## dataview

好像之前也有人提过这个问题，刚刚又研究了好久……放弃了……暂时不打算修这个

**Comment by laogao2005** [comment]
好的，谢谢你的回答

**Comment by LincZero** [comment]
![图片](https://github.com/user-attachments/assets/adcd1d2d-4c65-4d14-86d3-efc209558301)

@laogao2005 下版本提高了兼容性

新增支持 buttons、metabind、dataview inline js
