### ISSUE TITLE
[功能请求] scroll 对MD格式的表格无效

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#7]
scroll 处理器对列表转化的表格有效，但对MD用`|`和`-----`构建的表格无效。

| scroll与MD表格 | scroll语句 | 实时预览               | 阅读模式               |
| -------------- | ---------- | ---------------------- | ---------------------- |
| 没有空一行     | 无效       | MD表格可正确渲染为表格 | MD表格无法渲染为表格   |
| 有空一行       | 无效       | MD表格可正确渲染为表格 | MD表格可正确渲染为表格 |

测试环境：
- Windows 11 22H2
- Obsidian 1.1.9 沙箱仓库中仅安装Any Block插件1.3.1

scroll与MD表格没有空一行:

![image](https://user-images.githubusercontent.com/20738431/219031057-13a5f54a-c998-47d8-a207-706a43132e20.png)

scroll与MD表格有空一行:

![image](https://user-images.githubusercontent.com/20738431/219031173-2c050d41-6c37-4a64-9517-32177351bb9e.png)

**Comment by LincZero** [comment]
原因：没有表格选择器（目前支持的选择器类型只有：列表、引用块、代码块、标题）

暂时不计划增添选择器类型，不在短期TODO，但会列入长期计划中。

要增添选择器的话，在我的设计中又得加一大堆：
- 表格选择器
- 单段选择器（对正文生效，遇到空行自动结束）
- 仿vuepPress的首尾选择器
- 负级列表选择器

**Comment by Linzeal** [comment]
原来是没有表格选择器，难怪。

其实，表格选择器的开发优先级可以调高到与TREE同级，毕竟MD表格本身就是一个严格的TREE。AB将TREE转化渲染为表格，却对MD表格本身无法处理就有些拖后腿了。

而且MD表格的用户使用率高，若是有表格选择器，可以解决很多用户的痛点。反而TREE本身，用户没什么痛点，能转化渲染为表格，是方便按表格来看，很不错；但不转化渲染为表格，列表无非就像以前那样使用，不会有太多可惜。除非在AB基础上的可视化编辑功能具备了，列表转表格的用户粘性就会非常大了。

所以，建议功能无需平铺开，各个都开发，应先抓用户痛点，满足需求，定功能小核心，小核心不要追求完美，但要确保用户数据的完整性和安全性（**因此我强烈建议选择器与块之间无论是否有空白行相隔都能生效，并在DEMO中以隔一行做为范例引导用户从开始就习惯选择器与块隔一行来书写，以免AB意外不生效或卸载了，MD原本的渲染还能正常表达**），差不多相对稳定了，就**以最快速度上架市场，让大量的用户知道、使用、反馈**，再依此重新判断用户痛点，再排TODO优先级，进一步解决用户痛点、提高用户粘性。很多开发想法，会在有大量用户之后想的和一开始想的完全不一样了，尤其是功能选取上。
