### ISSUE TITLE
list2pumlWBS块支持画遗传系谱图吗

### ISSUE THREAD

**Issue by RectalGod** [LincZero/obsidian-any-block#70]
你好作者, 我发现list2pumlWBS块的根如果存在两个就会出错, 例如, 我想用list2pumlWBS实现遗传系谱图时, 像这样:

[list2pumlWBS]
- 多指患者甲
	- 正常子代甲
	- 多指患者
	- 正常子代乙
- 多指患者乙
	- 正常子代甲
	- 多指患者
	- 正常子代乙

**Comment by LincZero** [comment]
plantUML的WBS图必须要有且只能有一个根，不想额外多写一层也有个语法糖能在指令中把根节点加进去

![图片](https://github.com/user-attachments/assets/30672fb3-7311-4ed5-8cba-451e803a53d1)

这是PlantUML库的特性，不是我插件定义的行为
