### ISSUE TITLE
你好作者, Callouts内支持嵌入any block吗

### ISSUE THREAD

**Issue by RectalGod** [LincZero/obsidian-any-block#71]
例如这样
>[!info] test
>[list2mermaid]
- A
	- B
		- C

**Comment by LincZero** [comment]
## 旧版本临时解决

![图片](https://github.com/user-attachments/assets/b679d25e-e307-4cc0-84fb-7cd42afe65a9)

当前版本有一些支持方式：使用anyblock提供的callout而非ob自带的callout

## 下版本修复

7b7b4aecb1702353dfaa700117df6dc0febd945e

可以正常在callout中使用anyblock

![图片](https://github.com/user-attachments/assets/dd62f0b7-1e88-4dba-8dd1-ff99893e8a83)

但仅实时模式支持，阅读AnyBlock没提供嵌套判断AnyBlock的逻辑。如果想要能够在阅读模式下生效，还得用回 ”旧版本临时解决“ 中的方案

**Comment by LincZero** [comment]
3.1.6-beta2版本已经修复，未发布正式版本，需手动下载安装

https://github.com/LincZero/obsidian-any-block/releases/tag/3.1.6-beta

**Comment by RectalGod** [comment]
> 3.1.6-beta2版本已经修复，未发布正式版本，需手动下载安装
> 
> [https://github.com/LincZero/obsidian-any-block/releases/tag/3.1.6-beta ](https://github.com/LincZero/obsidian-any-block/releases/tag/3.1.6-beta)

爱你作者♥️
