### ISSUE TITLE
长期 - 优化vuepress/vitepress中anyblock的安装和配置体验，目前的配置方式还是略麻烦，不太满意

### ISSUE THREAD

**Issue by DaisyHunter** [LincZero/obsidian-any-block#72]
不知道是否配置正确。

我尝试把`ABConverter`文件夹复制到`node_modules\ABConverter`，然后在`/.vitepress`下的`config.mts`添加了
```
import { withMermaid } from "vitepress-plugin-mermaid";
import mathjax3 from "markdown-it-mathjax3";
+ import ABConverter from 'ABConverter';
```
但是不知道为何没有正确渲染
```
# Any Block

[listroot(root((mindmap)))|list2mindmap]

- Origins
  - Long history
  - ::icon(fa fa-book)
  - Popularisation
    - British popular psychology author Tony Buzan
- Research
  - On effectiveness<br/>and features
  - On Automatic creation
    - Uses
      - Creative techniques
      - Strategic planning
      - Argument mapping
- Tools
  - Pen and paper
  - Mermaid
```
![image](https://github.com/user-attachments/assets/730fe5f1-267a-42b3-b3d3-14e96b8391ec)

**Comment by LincZero** [comment]
我封装和部署文档弄得不算太好，主要是之前没啥人需要。这两天我写下文档&帮你看看。

因为是mdit插件，理论vitepress和vuepress都是可用的，但我其实没实践过。我网站那个是vuepress来的。我还得跑一下vitepress

**Comment by LincZero** [comment]
搞了下npm版的安装方式，还是有些问题……配置起来也不算太方便

在线文档：https://linczero.github.io/MdNote_Public/ProductDoc/AnyBlock/docs/zh/04.%20%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8_VuePress%E7%89%88.html

![image](https://github.com/user-attachments/assets/4f74d0e6-d844-486e-b487-3369b35e664b)

**Comment by DaisyHunter** [comment]
> ## Demo
> * https://github.com/any-block/VuepressDemo 提供了一个使用AnyBlock的最小仓库 (**vuepress2** 环境，使用npm方案)，并列出了从零构建该仓库的某一步的过程
> * https://github.com/any-block/VitePressDemo 提供了一个使用AnyBlock的最小仓库 (**vitepress** 环境，使用npm方案)，并列出了从零构建该仓库的某一步的过程
> * https://github.com/LincZero/LincZero.github.io 提供了一个使用AnyBlock的仓库 (**vuepress-theme-hope** 环境，使用源码方案，但这个仓库不是demo仓库，有很多其他的东西可能会影响参考)

感谢大佬的辛勤付出！插件非常的好使！🥰✌️🫰🤙👍
