### ISSUE TITLE
[question] 你好作者, 现阶段anyblock是否存在实现以下系谱图的语法

### ISSUE THREAD

**Issue by RectalGod** [LincZero/obsidian-any-block#73]
某一先天性肌强直家系的系谱图
![IMG_20240928_194434](https://github.com/user-attachments/assets/89d1a2cb-e693-4d5a-bfae-993d108b235a)

**Comment by LincZero** [comment]
不支持，这种图如果文字描述图表 (mermaid、plantuml) 也很勉强，感觉用一些图元绘制工具 (excalidraw、drow.io) 之类的画会好一些。

这方面的问题和技巧可以到论坛或群里交流询问
