### ISSUE TITLE
[bug] 实时模式和阅读模式下, 给[list2table]中的文本加脚注, 脚注不会转为可交互样式

### ISSUE THREAD

**Issue by RectalGod** [LincZero/obsidian-any-block#76]
例如, 给[list2table]中的文字加脚注[^12], 退出block编辑区, 脚注处会显示纯文本"12", 而不会不会转为可交互样式

**Comment by LincZero** [comment]
我试了下，结果是 `^12` 不显示，但能正常被 `[[^12]]` 跳转过去

**Comment by RectalGod** [comment]
> 我试了下，结果是 `^12` 不显示，但能正常被 `[[^12]]` 跳转过去

不对, [[*]]是绑定其他文章, 而[^*]是绑定本文章的脚注

**Comment by RectalGod** [comment]
> > 我试了下，结果是  `^12` 不显示，但能正常被  `[[^12]]` 跳转过去
> 
> 不对, [[*]]是绑定其他文章, 而[^*]是绑定本文章的脚注

实时模式
![图片](https://github.com/user-attachments/assets/a2a26319-00b1-4c97-88ab-6d35d11198ca)
编辑模式
![图片](https://github.com/user-attachments/assets/083d3d80-6cea-4f01-9dc4-4248780ead06)
![图片](https://github.com/user-attachments/assets/3856488e-43da-4fdd-b96d-fdbe55593101)

**Comment by RectalGod** [comment]
obsidian脚注语法: [^*] + [^*]:
![图片](https://github.com/user-attachments/assets/c4a0ed41-ead6-424d-96e7-a5e59d4bdbbf)

**Comment by LincZero** [comment]
我以为是用作跳转的脚注，原来是用作备注的脚注。我再研究下

**Comment by RectalGod** [comment]
> 我以为是用作跳转的脚注，原来是用作备注的脚注。我再研究下

谢谢作者么么么💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋

**Comment by LincZero** [comment]
因为AnyBlock渲染出来的结果是HTML结果而非CM结果，即渲染出来的效果是在阅读模式中的效果，而脚注在阅读模式下不显示。

如果要解决这个问题，首先要让你的ob能在阅读模式下能看到脚注，然后应该就能正常显示了

**Comment by LincZero** [comment]
或者更贴切的比喻是：

你在文件A使用脚注，在文件B用 `![[]]` 引用文件A，并显示出来。此时也看不到文件A中的脚注
