### ISSUE TITLE
[功能请求] addClass 对MD格式的表格无效

### ISSUE THREAD

**Issue by Linzeal** [LincZero/obsidian-any-block#8]
addClass处理器对列表转化的表格有效，但对MD用`|`和`-----`构建的表格无效。（测试时仅仅很简单的用类给表格字体设了`color: red;`）

| addClass与MD表格 | addClass语句 | 实时预览               | 阅读模式               |
| ---------------- | ------------ | ---------------------- | ---------------------- |
| 没有空一行       | 无效         | MD表格可正确渲染为表格 | MD表格无法渲染为表格   |
| 有空一行         | 无效         | MD表格可正确渲染为表格 | MD表格可正确渲染为表格 |

测试环境：
- Windows 11 22H2
- Obsidian 1.1.9 沙箱仓库中仅安装Any Block插件1.3.1

addClass与MD表格没有空一行：
![image](https://user-images.githubusercontent.com/20738431/219035644-ce189c7c-715d-438f-8321-bfa44301d0e6.png)

addClass与MD表格有空一行：
![image](https://user-images.githubusercontent.com/20738431/219035786-ace5d9ca-ba03-48a9-8df9-77df957d60a5.png)

**Comment by LincZero** [comment]
同 #7，同一个问题
